---
# handlers file for pia-ansible-role
- name: Remove local certificates
  file:
    path: '{{pia_ssl_directory_local}}'
    state: absent
  become: no
  delegate_to: localhost

- name: Remove local authkey
  file:
    path: '{{pia_auth_key_directory_local}}'
    state: absent
  become: no
  delegate_to: localhost
