---
- block:
    - name: Check if fluentd directory exists
      stat:
        path: '{{ pia_fluentd_path }}'
      register: result

    - name: Disable fluentd container
      docker_compose:
        project_src: '{{ pia_fluentd_path }}'
        state: absent
      when: result.stat.exists
  #End of block
  when: not pia_fluentd_enabled|bool

- block:
    ################################################################################################################
    # Fluentd setup
    ################################################################################################################
    - name: Prepare directory
      file:
        path: '{{ pia_fluentd_path }}'
        state: directory

    ################################################################################################################
    # Fluentd configuration
    ################################################################################################################

    - name: Copy configuration - sanitize vars selector
      fail:
        msg: "'pia_fluentd_output' have to be one of this options: {{ pia_fluentd_output_options }}"
      when: pia_fluentd_output not in pia_fluentd_output_options

    - name: Copy configuration - loki storage
      template:
        src: ./templates/loki.conf.j2
        dest: '{{ pia_fluentd_path }}/pia.conf'
      register: fluentd_config_loki
      when: pia_fluentd_output == "loki"

    - name: Copy configuration - file storage
      template:
        src: ./templates/file.conf.j2
        dest: '{{ pia_fluentd_path }}/pia.conf'
      register: fluentd_config_file
      when: pia_fluentd_output == "file"

    - name: Copy script for local log management
      template:
        src: ./templates/logs-management.sh.j2
        dest: '{{ pia_fluentd_path }}/logs-management.sh'
      when: pia_fluentd_output == "file"

    - name: Set up cron job for local log management
      ansible.builtin.cron:
        name: PIA log management
        minute: '0'
        hour: '4'
        job: '{{ pia_fluentd_path }}/logs-management.sh'
      when: pia_fluentd_output == "file"

    - name: Delete cron job for local log management
      ansible.builtin.cron:
        name: PIA log management
        state: absent
      when: pia_fluentd_output != "file"

    ################################################################################################################
    # Fluentd run
    ################################################################################################################

    - name: Copy docker-compose
      template:
        src: ./templates/docker-compose.yml.j2
        dest: '{{ pia_fluentd_path }}/docker-compose.yml'

    - name: Copy .env
      template:
        src: ./templates/.env.j2
        dest: '{{ pia_fluentd_path }}/.env'

    - name: Restart
      docker_compose:
        project_src: '{{ pia_fluentd_path }}'
        recreate: always
        build: no
        pull: yes
      vars:
        ansible_python_interpreter: /sormas/venv/bin/python
      when: fluentd_config_loki.changed or fluentd_config_file.changed | bool
      register: fluent_restarted

    - name: Run
      docker_compose:
        project_src: '{{ pia_fluentd_path }}'
        build: no
        pull: yes
      vars:
        ansible_python_interpreter: /sormas/venv/bin/python
      when: not fluent_restarted.changed

  #End of block
  #Legacy cause this conditional to be pretty rough... It will be run only on one host from inventory
  when: (pia_fluentd_enabled|bool) and (pia_url is defined) and (inventory_hostname == pia_url)
