---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: create directory
      file:
        path: ./generated
        state: directory
    - name: template docker-compose.yml
      template:
        src: ./templates/docker-compose.yml.j2
        dest: ./generated/docker-compose.yml
    - name: template .env
      template:
        src: ./templates/env.j2
        dest: ./generated/.env
