- vars:
    ansible_python_interpreter: /usr/bin/python3
  tags:
    - prerequisites
  block:
    - name: Push authKey private to qpia
      copy:
        src: '{{ pia_auth_key_directory_local }}/private.key'
        dest: '{{ pia_auth_key_directory }}/private.key'
        mode: '0600'
        owner: '1000'
      when: pia_is_qpia

    - name: Push authKey public to qpia, ewpia and ipia
      copy:
        src: '{{ pia_auth_key_directory_local }}/public.pem'
        dest: '{{ pia_auth_key_directory }}/public.pem'
        mode: '0600'
        owner: '1000'
      when: (pia_is_qpia or pia_is_ipia or pia_is_ewpia)
