################################################################
### Generate CA
################################################################
- delegate_to: localhost
  run_once: true
  become: no
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tags:
    - prerequisites
  block:
    - name: Generate temporary directory for generated certificates
      tempfile:
        state: directory
        prefix: pia-authkey-
      register: result
      notify:
        - Remove local authkey
      when: pia_auth_key_directory_local is not defined

    - set_fact:
        pia_auth_key_directory_local: '{{result.path}}'
      when: pia_auth_key_directory_local is not defined

    - name: Create authKey directory
      file:
        path: '{{ pia_auth_key_directory_local }}'
        state: directory

    - name: Generate authKey private
      command: openssl genrsa -out {{ pia_auth_key_directory_local }}/private.key 4096
      args:
        creates: '{{ pia_auth_key_directory_local }}/private.key'

    - name: Generate authKey public
      command: openssl rsa -in {{ pia_auth_key_directory_local }}/private.key -pubout -out {{ pia_auth_key_directory_local }}/public.pem
      args:
        creates: '{{ pia_auth_key_directory_local }}/public.pem'
