################################################################
### Generate CA
################################################################
- delegate_to: localhost
  run_once: true
  become: no
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tags:
    - prerequisites
  block:
    - name: Generate temporary directory for generated certificates
      tempfile:
        state: directory
        prefix: pia-certs-
      register: result
      notify:
        - Remove local certificates
      when: pia_ssl_directory_local is not defined

    - set_fact:
        pia_ssl_directory_local: '{{result.path}}'
      when: pia_ssl_directory_local is not defined

    - name: Create directory for certs
      file:
        path: '{{pia_ssl_directory_local}}'
        state: directory

    - name: Create ca.key
      openssl_privatekey:
        path: '{{ pia_ssl_directory_local }}/ca.key'

    - name: Generate the CSR file signed with the private key
      openssl_csr:
        basic_constraints: CA:TRUE
        basic_constraints_critical: true
        path: '{{ pia_ssl_directory_local }}/ca.csr'
        privatekey_path: '{{ pia_ssl_directory_local }}/ca.key'
        common_name: 'PIA-CA'

    - name: Sign the CSR file as a CA to turn it into a certificate
      openssl_certificate:
        path: '{{ pia_ssl_directory_local }}/ca.cert'
        privatekey_path: '{{ pia_ssl_directory_local }}/ca.key'
        csr_path: '{{ pia_ssl_directory_local }}/ca.csr'
        provider: selfsigned

    ################################################################
    ### Generate certificates for Services
    ################################################################

    - name: Create directory
      file:
        path: '{{ pia_ssl_directory_local }}/{{ item.fullName }}/'
        state: directory
      with_items: '{{ pia_services }}'

    - name: Generate private key
      openssl_privatekey:
        path: '{{ pia_ssl_directory_local }}/{{ item.fullName }}/{{ item.name }}.key'
        size: 4096
      with_items: '{{ pia_services }}'

    - name: Generate an OpenSSL Certificate Signing Request with a passphrase protected private key
      openssl_csr:
        path: '{{ pia_ssl_directory_local }}/{{ item.fullName }}/{{ item.name }}.csr'
        privatekey_path: '{{ pia_ssl_directory_local }}/{{ item.fullName }}/{{ item.name }}.key'
        country_name: '{{ pia_ssl_country_name }}'
        state_or_province_name: '{{ pia_ssl_state_or_province_name }}'
        locality_name: '{{ pia_ssl_locality_name }}'
        organization_name: '{{ pia_ssl_organization_name }}'
        organizational_unit_name: '{{ pia_ssl_organizational_unit_name }}'
        common_name: '{{ item.fullName }}'
        #subject_alt_name: "DNS:localhost,DNS:{{ item.fullName }},IP:{{ survey_IP }}"
        subject_alt_name: 'DNS:localhost,DNS:{{ item.fullName }}'
      with_items: '{{ pia_services }}'

    - name: Generate an OpenSSL certificate signed with your own CA certificate
      openssl_certificate:
        path: '{{ pia_ssl_directory_local }}/{{ item.fullName }}/{{ item.name }}.cert'
        csr_path: '{{ pia_ssl_directory_local }}/{{ item.fullName }}/{{ item.name }}.csr'
        ownca_path: '{{ pia_ssl_directory_local }}/ca.cert'
        ownca_privatekey_path: '{{ pia_ssl_directory_local }}/ca.key'
        selfsigned_not_after: '+3650d'
        provider: ownca
      with_items: '{{ pia_services }}'
