---
- hosts: all
  roles:
    - pia-fluentd
  tasks:
    - name: Include pia-ansible role for sormas sb
      include_role:
        name: pia
      when:
        - pia_url is defined
        - inventory_hostname == pia_url
        - not pia_multi_host|bool

    - name: Include pia-ansible role for multi host pia
      include_role:
        name: pia
      when: pia_multi_host|bool
